### ISSUE TITLE
Some text in powershell is not readable

### ISSUE THREAD

**Issue by dnperfors** [thismat/nord-windows-terminal#1]
Hi,
Thanks for this unofficial port of Nord.
I am just trying it out and noticed that when I run in PowerShell (Core): `winget --help` the `--help` is hardly readable.

**Comment by thismat** [comment]
Hey,

Thanks for the heads up. Do you have a screenshot of the behavior you're seeing?

**Comment by dnperfors** [comment]
Sure:
![image](https://user-images.githubusercontent.com/170992/146208157-fdebfc10-8d89-4e8c-b9b0-3e625bff0b22.png)
Strangely enough, in the screenshot the text is slightly better readable.

**Comment by thismat** [comment]
Got it. Will have to take a look and see if there are better alternatives for this color. Thanks for the report.

**Comment by Kellegram** [comment]
This is a problem with Nord in general and it's why whenever I use popular themes I do not apply them in the way the authors expect them, as too much focus is put into sticking to the theme and too little to accessibility. Nord is known to have barely readable comments (there's even a theme for vs code called "Nord deep but you can actually see comments" lol).

I used #6f6f85 instead, It's infinitely more readable, personal preference though, could just use the same as the vscode theme I mentioned.

**Comment by antoineco** [comment]
On macOS I use the Kitty terminal, which [Nord theme](https://github.com/kovidgoyal/kitty-themes/blob/f6c2f4e5/themes/Nord.conf#L20-L22) has
- [nord1](https://www.nordtheme.com/docs/colors-and-palettes#nord1) for black (`#3B4252`)
- [nord3](https://www.nordtheme.com/docs/colors-and-palettes#nord3) for bright black (`#4C566A`)
 
The Nord theme for Alacritty — which is _official_ — uses the [same values](https://github.com/arcticicestudio/nord-alacritty/blob/940c88a6/src/nord.yml#L32-L49).

In comparison, this theme uses [nord1](https://www.nordtheme.com/docs/colors-and-palettes#nord1) (`#3B4252`) for both black and bright black, which seems problematic based on the screenshot shared in the issue description, and also my own experience.

Switching the color is a slight improvement, and looks more like on other platforms:

![image](https://user-images.githubusercontent.com/3299086/182127884-312ea5c4-40e4-49e5-b17d-a73606a36816.png)

---

Note:

Most other color variations seem to differ from official themes:
- foreground should be [nord4](https://www.nordtheme.com/docs/colors-and-palettes#nord4) (`#D8DEE9`) but here it is [nord5](https://www.nordtheme.com/docs/colors-and-palettes#nord5) (`#E5E9F0`)
- both red and bright red should be [nord11](https://www.nordtheme.com/docs/colors-and-palettes#nord11) (`#BF616A`), but here bright red is [nord12](https://www.nordtheme.com/docs/colors-and-palettes#nord12) (`#D08770`)
- both blue and bright blue should be [nord9](https://www.nordtheme.com/docs/colors-and-palettes#nord9) (`#81A1C1`), but here bright blue is [nord10](https://www.nordtheme.com/docs/colors-and-palettes#nord10) (`#5E81AC`) (which is in fact _darker_ than the non-bright color)
- both green and bright green should be [nord14](https://www.nordtheme.com/docs/colors-and-palettes#nord14) (`#A3BE8C`), but here green is [nord7](https://www.nordtheme.com/docs/colors-and-palettes#nord7) (`#8FBCBB`)
- cyan should be [nord8](https://www.nordtheme.com/docs/colors-and-palettes#nord8) (`#88C0D0`) and bright cyan should be [nord7](https://www.nordtheme.com/docs/colors-and-palettes#nord7) (`#8FBCBB`), but here both cyan and bright cyan are [nord8](https://www.nordtheme.com/docs/colors-and-palettes#nord8) (`#88C0D0`)
- white should be [nord5](https://www.nordtheme.com/docs/colors-and-palettes#nord5) (`#E5E9F0`) and bright white should be [nord6](https://www.nordtheme.com/docs/colors-and-palettes#nord6) (`#ECEFF4`), but here white is [nord4](https://www.nordtheme.com/docs/colors-and-palettes#nord4) (`#D8DEE9`)

This was all probably deliberate, but it is worth noting that this theme _will_ differ from official terminal themes.

A modified version of this theme that is better aligned with the official ports is available here: https://github.com/antoineco/dotfiles/blob/f3ee3463/WindowsTerminal/Fragments/nord/nord.json

**Comment by thismat** [comment]
Thanks a lot for the information!

When I set up the theme I wasn't going based on official ports - just off the spec of the Nord. I don't recall all of my reasonings other than trying to follow the spec but looking at the other official ports for terminals makes sense, some adjustments need to be made.

Appreciate all the time you put into this, if you want to merge your changes with this repo feel free to open a PR, otherwise I'll try to get to the changes as I have time.

**Comment by antoineco** [comment]
Glad to hear you're considering merging them! I assumed you had your own reasons for preferring certain colors, which is why I didn't want to submit a PR too fast.

**Comment by thismat** [comment]
@antoineco I appreciate all the work you put into this. 🥳
