### ISSUE TITLE
tabRow color

### ISSUE THREAD

**Issue by DLopezGo90** [thismat/nord-windows-terminal#5]
Is there a way to change the colors of the selected window and the rest of the tabRow?

![image](https://user-images.githubusercontent.com/59780264/211222604-980ce892-a6e6-4318-b3c6-41f0bf4f2c96.png)

**Comment by thismat** [comment]
To my current knowledge I don't think there is a way to do theme this with Windows Terminal yet. You might be able to achieve this effect another way though:

Enable this experimental feature: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/appearance#use-a-background-image-for-the-entire-window

And then set a background image with the nord background color. I have not tested this, but it could work.

Good luck!
